### PR TITLE
Add parent_write_txn parameter to create db calls

### PR DESCRIPTION
**Pull request by sphw**
This PR adds two to function calls that allow the user to pass in an existing write_txn to the create_database functions.

I believe this should still be safe since we use a nested transaction and still commit it before releasing the lock

### CODE REVIEW

**Comment by Kerollmops** [comment]
Hey,

Thank you @sphw for this PR.
It would be better if the `raw_create_database` function always accepts a transaction, `create_database` and `create_poly_database` then start a write transaction and give it to the `create_database_with_txn` and `create_poly_database_with_txn` respectively.

What do you think?

Also next time could avoid formatting the code please, it would be easier for me to review the changes, or do it in another commit, no worries :)

**Comment by sphw** [comment]
Yeah that makes more sense. I'll modify it to do that.

I'll try and remove the formatting as well, my editor does it automatically

**Comment by sphw** [comment]
@Kerollmops I have updated the PR with the changes. One minor downside to this method is that we create two transactions for `create_database` instead of one. This will probably have a minor affect on performance. I suspect it won't be a problem in the real world since database creation won't happen very often.

**Comment by Kerollmops** [comment]
Hum... Yeah, you are right, I didn't thought about this. This is like you said, not that impactfull.

Could you rebase on master, please? I have merged another PR, I will merge just after you rebased :)

**Comment by sphw** [comment]
> Hum... Yeah, you are right, I didn't thought about this. This is like you said, not that impactfull.
> 
> Could you rebase on master, please? I have merged another PR, I will merge just after you rebased :)

Done

**Comment by Kerollmops** [comment]
Thank you!

**Pull request merged**
