### PR TITLE
Use mdb_stat for db.len()

### LINKED ISSUE #56: Improve the poly/database length function
We currently create an iterator count the number of entries to returns to compute the number of entries a database stores.

There is a better way that is not `O(n)` which is using [the `num_entries` field of the `Stat` struct](https://github.com/mozilla/lmdb-rs/blob/df1c2f56e3088f097c719c57b9925ab51e26f3f4/lmdb-sys/src/bindings.rs#L182-L183) that is returned by [the `mdb_stat` function](https://github.com/mozilla/lmdb-rs/blob/df1c2f56e3088f097c719c57b9925ab51e26f3f4/lmdb-sys/src/bindings.rs#L882-L895).

### PR DESCRIPTION
**Pull request by Keats**
Closes #56

### CODE REVIEW

**Comment by Kerollmops** [comment]
Hey, thank you for the changes but could you change the base branch, please? You can do that by clicking the EDIT button for changing the title and move it to the `v0.11` branch.

The changes that you are introducing are breaking and I must publish a new breaking version, the 0.11.0 one, I would like to make some more breaking changes in this version (#87, #91, and maybe #89) what do you think?

**Comment by Kerollmops** [comment]
Hum... it seems like you also need to rebase (or cherry-pick) your commit on the v0.11 branch too! Sorry about that.

**Comment by Keats** [comment]
> Hum... it seems like you also need to rebase (or cherry-pick) your commit on the v0.11 branch too! Sorry about that.

yep doing it now

**Comment by Kerollmops** [comment]
Note that I will maybe also [bump the libmdbx version used by heed right now, from 0.7.1 to 0.9.2](https://github.com/Kerollmops/mdbx-rs/pull/4). What do you think about waiting for this PR to be merged and being able to bump the heed mdbx dependency?

**Comment by Keats** [comment]
https://github.com/Kerollmops/heed/pull/100 for the clean PR.
As for breaking changes it looks ok, but it would be good to see where https://github.com/Kerollmops/heed/pull/91/files#diff-ba6e7475acd6f0ab6e49c1ab56ea00c887d3f436dcd32acc0d927cf901ec8fb2 is coming from

**Comment by Keats** [comment]
> Note that I will maybe also bump the libmdbx version used by heed right now, from 0.7.1 to 0.9.2. What do you think about waiting for this PR to be merged and being able to bump the heed mdbx dependency?

Works for me, I'm not in a hurry.

**Comment by Kerollmops** [comment]
> [...] but it would be good to see where https://github.com/Kerollmops/heed/pull/91/files#diff-ba6e7475acd6f0ab6e49c1ab56ea00c887d3f436dcd32acc0d927cf901ec8fb2 is coming from

This code comes from the zerocopy crate, and you are right I will not merge that one for the v0.11.

**Pull request closed without merging**
