### PR TITLE
Support windows and make the tests pass

### LINKED ISSUE #24: Make it compile and work on Windows
```
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\heed-0.5.0\src\env.rs:5:14
  |
5 | use std::os::unix::io::AsRawFd;
  |              ^^^^ could not find `unix` in `os`

error[E0599]: no method named `as_raw_fd` found for type `std::fs::File` in the current scope
   --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\heed-0.5.0\src\env.rs:307:23
    |
307 |         let fd = file.as_raw_fd();
    |                       ^^^^^^^^^ method not found in `std::fs::File`

error: aborting due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by Kerollmops**
Hello potential contributor,

I am currently working on making [MeiliSearch](https://github.com/meilisearch/MeiliSearch) compile on Windows. The only remaining dependency to update seems to be heed.
In this pull request I use [a fork of the lmdb-sys crate](https://github.com/mozilla/lmdb-rs/compare/master...Kerollmops:support-windows-filehandle) that seems to compile on Windows. The issue is that even with this fork I am not able to find where I am wrong and why I get [this error message](https://github.com/Kerollmops/heed/runs/321172595#step:4:113). I don't have a Windows computer at hand and would be glad if someone could help me tackle this :)

Will be fixed when https://github.com/mozilla/lmdb-rs/pull/74 is merged.

Closes #24.

### CODE REVIEW

**Comment by maroider** [comment]
I'm willing to help debug this issue.

**Comment by Kerollmops** [comment]
Ho! Thank you @maroider !

I wanted to make heed work on Windows, I added the support of windows file descriptors in lmdb-sys (on linux its an `int`, on Windows its `a pointer`). I tried to make the tests pass but its hard to debug when you don't have the Windows machine at hand.

So, here you are, helping me tackle [this issue](https://github.com/Kerollmops/heed/runs/321172595#step:4:113) with your Windows machine I presume? 😃

Would it be possible to clone the repository, checkout the `support-windows` branch and try to understand where I "miss typed" a file name, please?

Thank you very much!

**Comment by gentoid** [comment]
I'd like to help too. @maroider please let me know if you need some assistance

**Comment by Kerollmops** [comment]
Thank you @gentoid for your help :)

**Comment by maroider** [comment]
The issue originates in [`EnvOpenOptions::open`](https://github.com/Kerollmops/heed/blob/4399d5c5ada4696c578f99da96e197c8d4e359e8/src/env.rs#L123-L172).
Removing [`path.cannonicalize()?;`](https://github.com/Kerollmops/heed/blob/4399d5c5ada4696c578f99da96e197c8d4e359e8/src/env.rs#L125) and adding `path.to_path_buf();` makes the test suite pass.
The offending line was introduced in bab25b727b85bc7369222a031d9e704d185dcabf. Could you perhaps shed some light on why the path is cannonicalized here, @Kerollmops?

**Comment by Kerollmops** [comment]
Thank you for this great debug.

I originally canonicalized the path to make sure that a environment is correctly identified by its path and not by a relative path (i.e. `../folder1/../folder1/db` must be equal to `../folder1/db`).

This way I can be sure that not to different types of data are read from the same environment.

I originally thought that [LMDB prohibited opening the same environment multiple times](http://www.lmdb.tech/doc/group__mdb.html#ga32a193c6bf4d7d5c5d579e71f22e9340) with the same program but it seems like [mozilla/lmdb-rkv doesn't handle this issue](https://github.com/mozilla/lmdb-rs/blob/5f5245ad4d7cd59388cb08577daad92f24a946c2/src/environment.rs#L383-L435).

So, I think that it is still needed to ensure a same environment is not opened with different database types, if we are not able to create canonicalized paths on Windows, we will make it work on unix systems at least.

**Comment by Kerollmops** [comment]
Ok, so thanks to you I search in the codebase of the `mozilla/rkv` database based on LMDB and found out how they work around the Windows Path problem.

https://github.com/mozilla/rkv/blob/7da5bd021decb82e163b3cbd1e5b8d84ec354aa2/src/manager.rs#L46-L58

I will rebase this PR on master and make the required changes.

Thank you for your help @maroider and @gentoid !

**Comment by Kerollmops** [comment]
Awesome, it compiles thanks to you and this workaround!
The only remaining thing is that my other PR is merged and I will be able to release a new heed version that works on Windows!

**Pull request merged**
